# Generated by Django 5.1.4 on 2025-01-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("descriptionCoffe", "0001_initial"),
        ("typeCoffe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="companyCoffe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("resume", models.TextField(blank=True, null=True)),
                (
                    "descriptioncoffe",
                    models.ManyToManyField(
                        related_name="choices", to="descriptionCoffe.descriptioncoffe"
                    ),
                ),
                (
                    "typecoffe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices",
                        to="typeCoffe.typecoffe",
                    ),
                ),
            ],
        ),
    ]
